all: test/util/GraphTest
SRC_TEST_UTIL := test/util/GraphTest.cpp \
    util/debug.cpp 

OBJS_TEST_UTIL= $(SRC_TEST_UTIL:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_TEST_UTIL)))

test/util/GraphTest: $(OBJS_TEST_UTIL)
	$(CXX) $(CXXFLAGS) -o test/util/GraphTest $(OBJS_TEST_UTIL) $(LIB_TEST)



	
