all: util/graph/graph 
SRC_GRAPH := util/debug.cpp 

OBJS_GRAPH= $(SRC_GRAPH:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_GRAPH)))

util/graph/graph: $(OBJS_GRAPH) $(LIBMODELICA)
	$(CXX) $(CXXFLAGS) -o util/graph/graph $(OBJS_GRAPH) -L./lib -lmodelica



	
